[package]
name = "dino-token"
version = "1.0.0"
authors = ["Rudi114, whoislewys"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"